### ISSUE TITLE
Server crashes with X Error

### ISSUE THREAD

**Issue by dwoznicki** [acalcutt/tileserver-gl#2]
I've gotten the tileserver running, but I'm running into an issue when I try to load a page. Here's the console output:

```
13:40:14 ❯ PORT=8005 tileserver-gl --mbtiles zurich_switzerland.mbtiles
Starting @acalcutt/tileserver-gl v4.0.8
[INFO] Automatically creating config file for zurich_switzerland.mbtiles
[INFO] Only a basic preview style will be used.
[INFO] See documentation to learn how to create config.json file.
Run with --verbose to see the config file here.
Starting server
Listening at http://[::]:8005/
Startup complete
GET /index.css 304 17.900 ms - -
GET /images/logo.png 304 26.502 ms - -
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  153 (GLX)
  Minor opcode of failed request:  27 (X_GLXCreatePbuffer)
  Serial number of failed request:  37
  Current serial number in output stream:  40
```

I get this error when I try to run tileserver-gl on a Debian 11 machine when I try to load the home page.

Interestingly, running the server on my local desktop with Pop!_OS 20.04 (basically a reskin of Ubuntu 20.04) works a bit better, though the server still crashes when I try to load the raster tile map. Here's the console output there:

```
13:48:29 ❯ PORT=8005 tileserver-gl --mbtiles zurich_switzerland.mbtiles
Starting @acalcutt/tileserver-gl v4.0.8
[INFO] Automatically creating config file for zurich_switzerland.mbtiles
[INFO] Only a basic preview style will be used.
[INFO] See documentation to learn how to create config.json file.
Run with --verbose to see the config file here.
Starting server
Listening at http://[::]:8005/
Startup complete
GET / 200 108.850 ms - 2708
GET /index.css 200 10.189 ms - 3276
GET /images/logo.png 200 6.915 ms - 6407
GET /images/placeholder.png 200 7.988 ms - 2084
GET /images/header-map-1280px.png 200 4.169 ms - 174969
GET /fonts/OpenSans-Regular.ttf 200 4.563 ms - 217360
GET /fonts/OpenSans-Bold.ttf 200 4.503 ms - 224592
GET /styles/basic-preview/11/1072/717.png 200 289.960 ms - 54747
GET /favicon.ico 200 3.246 ms - 5430
GET /styles/basic-preview/?raster 200 22.524 ms - 3205
GET /maplibre-gl.css 200 2.113 ms - 68506
GET /maplibre-gl-inspect.css 200 1.189 ms - 1921
GET /leaflet.css 200 1.749 ms - 14004
GET /leaflet.js 200 1.981 ms - 143908
GET /leaflet-hash.js 200 3.239 ms - 3462
GET /L.TileLayer.NoGap.js 200 3.661 ms - 8137
GET /maplibre-gl.js 200 2.139 ms - 706133
GET /maplibre-gl-inspect.min.js 200 1.935 ms - 23455
GET /styles/basic-preview.json 200 2.960 ms - 479
GET /styles/basic-preview/11/1072/717.png 304 1.535 ms - -
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  153 (GLX)
  Minor opcode of failed request:  27 (X_GLXCreatePbuffer)
  Serial number of failed request:  30
  Current serial number in output stream:  37
```

Note that when the X error occurs, the service crashes. Any ideas on how to go about solving this?

EDIT: Okay, so I think the error I'm getting on my Debian server is being propagated from my local machine because of X forwarding. If I `ssh` into the Debian server *without* X forwarding turned on, I get a different error when I attempt to load a server page.

```
14:08:30 ❯ PORT=8005 tileserver-gl --mbtiles zurich_switzerland.mbtiles
Starting @acalcutt/tileserver-gl v4.0.8
[INFO] Automatically creating config file for zurich_switzerland.mbtiles
[INFO] Only a basic preview style will be used.
[INFO] See documentation to learn how to create config.json file.
Run with --verbose to see the config file here.
Starting server
Listening at http://[::]:8005/
Startup complete
GET / 304 280.505 ms - -
GET /index.css 304 51.538 ms - -
GET /images/logo.png 304 27.910 ms - -
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open X display.
Aborted
```

**Comment by dwoznicki** [comment]
I got it. I needed to run a mock X server using `xvfb-run`. I'm not sure if this is a great long term solution, but here's how I got the tile server up and running and serving raster tiles.

```bash
PORT=8005 xvfb-run -a tileserver-gl --mbtiles zurich_switzerland.mbtiles
```

**Comment by acalcutt** [comment]
Yes, that makes sense. on a headless system (not running X Server), xvfb needs to be run before tileserver-gl ( https://github.com/maptiler/tileserver-gl/issues/71 )

In my server, which I run tileserver-gl through systemd, I made a xvfb service
https://github.com/acalcutt/wifidb-tileserver-gl/blob/master/tileserver-gl/systemd/Xvfb.service 
then in my Tileserver service, I set the "Display" environment variable to made what the xvfb service uses
https://github.com/acalcutt/wifidb-tileserver-gl/blob/master/tileserver-gl/systemd/Tileserver.service

In the docker version, this script gets run which also starts xvfb-run
https://github.com/acalcutt/tileserver-gl/blob/main/docker-entrypoint.sh

**Comment by dwoznicki** [comment]
Cool, thanks for the links. Should I make a PR with info about this issue? Maybe as a TROUBLESHOOTING.md file?

Also, any idea about the first `X Error of failed request:  BadAlloc (insufficient resources for operation)` I was running into on my local computer? I'm trying to determine how much of a penalty we're paying for using `xvfb` instead of a dedicated GPU to do the rasterization.

**Comment by acalcutt** [comment]
I would love a PR to start a TROUBLESHOOTING.md file, or maybe a troubleshooting.rst in https://github.com/acalcutt/tileserver-gl/tree/main/docs . these docs get used by https://tileserver-gl.readthedocs.io/en/latest/

As for the other question, I'm not really sure as I haven't seen that one since I've run headless. I think GLX is a OpenGL error. I do see that error on google with various fixes

The top result shows adding Videoram and Cachelines to your X.org config. I have a hard time believing this is going to be the fix, but it could be worth a shot 
https://stackoverflow.com/questions/15577540/x-error-of-failed-request-badalloc-insufficient-resources-for-operation

Another one mentioned upgrading 'mesa', I know this uses mesa ([see here](https://tileserver-gl.readthedocs.io/en/latest/installation.html#npm)), so maybe make sure that libgles2-mesa package is installed?
https://stackoverflow.com/questions/9769613/x-error-badalloc-glx-badcontext-on-intelsandybridge-intel-hd-graphics-3000

I saw another article mention making sure the right screen was being targeted. maybe type 'export' in shell and see what the 'DISPLAY' environment variable is set to and that it matches the display in your xorg.conf ? I'm guessing it is probably already set, but maybe it doesn't exists and tileserver doesn't know which screen to target?

**Comment by acalcutt** [comment]
Also another thing could also be the maplibre-gl-native npm packages I created are made to target ubuntu-20.04 . I have found debian 11 is close enough where I can get it to work, however I'm not so sure about Pop!_OS 20.04.

If it really is just reskin its proably fine, bun maybe double check you have these Native Dependencies installed ( https://tileserver-gl.readthedocs.io/en/latest/installation.html#npm )

**Comment by dwoznicki** [comment]
Yeah, I tried the X.org config thing, but I had no luck with it. Seems like an unlikely candidate. I don't have libgles2-mesa installed, so I'll try giving that a shot. I'll also take a look at the native dependencies and see if I'm missing anything else.

Pop!_OS mirrors Ubuntu really closely, so I don't *think* that's the issue. When I trace through the binding stack with `LD_DEBUG=all tileserver-gl --mbtiles zurich_switzerland.mbtiles`, it looks like the BadAlloc error is thrown while attempting to run `fprintf_chk` (probably).

```
     11648: symbol=__fprintf_chk;  lookup in file=node [0]
     11648: symbol=__fprintf_chk;  lookup in file=/lib/x86_64-linux-gnu/libdl.so.2 [0]
     11648: symbol=__fprintf_chk;  lookup in file=/lib/x86_64-linux-gnu/libstdc++.so.6 [0]
     11648: symbol=__fprintf_chk;  lookup in file=/lib/x86_64-linux-gnu/libm.so.6 [0]
     11648: symbol=__fprintf_chk;  lookup in file=/lib/x86_64-linux-gnu/libgcc_s.so.1 [0]
     11648: symbol=__fprintf_chk;  lookup in file=/lib/x86_64-linux-gnu/libpthread.so.0 [0]
     11648: symbol=__fprintf_chk;  lookup in file=/lib/x86_64-linux-gnu/libc.so.6 [0]        
     11648: binding file /lib/x86_64-linux-gnu/libX11.so.6 [0] to /lib/x86_64-linux-gnu/libc.so.6 [0]: normal symbol `__fprintf_chk' [GLIBC_2.3.4]
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  153 (GLX)
```

**Comment by dwoznicki** [comment]
I'm starting to think this may be an issue with my AMD graphics card. When I search for "X_CLXCreatePbuffer", [things like this](https://www.mail-archive.com/virtualgl-users@googlegroups.com/msg00342.html) start to show up.

I also tried building maplibre-gl-native and running the test suite, and I hit the same issue on the Annotations test. Perhaps I'll make an issue over at maplibre-gl-native and see if anyone has any ideas.

**Comment by dwoznicki** [comment]
Here's my resolution: maplibre/maplibre-gl-native#282

**Comment by acalcutt** [comment]
That's so strange that is fails with the amd card. what model is the video card?

**Comment by dwoznicki** [comment]
I can get more info on Monday if you're curious, but here's the output from `glxinfo`.

```
10:17:45 ❯ glxinfo -B
name of display: :1
display: :1  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD OLAND (DRM 2.50.0, 5.16.19-76051619-generic, LLVM 12.0.0) (0x6613)
    Version: 21.2.2
    Accelerated: yes
    Video memory: 2048MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 1835 MB, largest block: 1835 MB
    VBO free aux. memory - total: 1953 MB, largest block: 1953 MB
    Texture free memory - total: 1835 MB, largest block: 1835 MB
    Texture free aux. memory - total: 1953 MB, largest block: 1953 MB
    Renderbuffer free memory - total: 1835 MB, largest block: 1835 MB
    Renderbuffer free aux. memory - total: 1953 MB, largest block: 1953 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 2048 MB
    Total available memory: 4091 MB
    Currently available dedicated video memory: 1835 MB
OpenGL vendor string: AMD
OpenGL renderer string: AMD OLAND (DRM 2.50.0, 5.16.19-76051619-generic, LLVM 12.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 21.2.2
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 21.2.2
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

It's some Radeon model, though I also had the same error with the onboard AMD graphics card as well.
