### ISSUE TITLE
Some labels appear cutoff in raster tiles

### ISSUE THREAD

**Issue by dwoznicki** [acalcutt/tileserver-gl#6]
I'm having an issue where some of the labels in raster tiles appear cutoff.

![image](https://user-images.githubusercontent.com/13933454/190001066-d18c2a75-3cac-4064-9dfe-70fff470c83a.png)

When I look at the actual image being generated, I can see that the labels are clearly being cutoff at the image boundaries.

![image](https://user-images.githubusercontent.com/13933454/190005128-d26abe5c-2907-4dbe-93a7-ce928043a41b.png)

This looks very much like [this issue in MapLibre GL Native](https://github.com/maplibre/maplibre-gl-native/issues/284) that @acalcutt raised. Reading through that thread, I got the impression that the issue should be fixed on master now, but I'm not totally sure if that's the case.

For reference, here's my npm package versions.

```
danwoz@flan tegola  master [!?] 
13:43:28 ❯ npm ls -g --depth 1
/home/danwoz/.nvm/versions/node/v16.15.0/lib
├─┬ @acalcutt/tileserver-gl@4.0.22
│ ├── @acalcutt/maplibre-gl-native@5.0.25
│ ├── @mapbox/glyph-pbf-composite@0.0.3
│ ├── @mapbox/mbtiles@0.12.1
│ ├── @mapbox/sphericalmercator@1.2.0
│ ├── @mapbox/vector-tile@1.3.1
│ ├── @maplibre/maplibre-gl-style-spec@17.0.1
│ ├── advanced-pool@0.3.3
│ ├── canvas@2.9.3
│ ├── chokidar@3.5.3
│ ├── clone@2.1.2
│ ├── color@4.2.3
│ ├── commander@9.4.0
│ ├── cors@2.8.5
│ ├── express@4.18.1
│ ├── handlebars@4.7.7
│ ├── http-shutdown@1.2.2
│ ├── morgan@1.10.0
│ ├── pbf@3.2.1
│ ├── proj4@2.8.0
│ ├── request@2.88.2
│ ├── sharp@0.30.7
│ └── tileserver-gl-styles@2.0.0
```

**Comment by acalcutt** [comment]
This should be fixed in v4.0.21+ . If you go to the main page it should say the version at the bottom. You on at least that version?

**Comment by acalcutt** [comment]
Also, if you aren't using the docker, don't forget to run an npm -i to update you packages...I've forgotten that a few times and was confused.

**Comment by dwoznicki** [comment]
It looks like my versions are properly updated (as far as I can tell).

![image](https://user-images.githubusercontent.com/13933454/190029708-4a5c3455-91c2-4746-8add-768df54ed678.png)

Also, when I run `npm ls --depth 1`, it reports that I have `@acalcutt/tileserver-gl@4.0.22` and `@acalcutt/maplibre-gl-native@5.0.25`.

**Comment by dwoznicki** [comment]
I'm on NodeJS v16.17.0, so it looks like my `process.versions.modules` is "93", btw.

**Comment by acalcutt** [comment]
v16.14.2 is what I am using here.

I tried to see if I can replicate it but in my style I don't see most of those clipped labels. Can you share your style?
![image](https://user-images.githubusercontent.com/3792408/190037128-b1726a79-2d27-4d0e-945f-12a0d8ea5c66.png)

**Comment by dwoznicki** [comment]
Yeah, you can find my configuration here: https://github.com/dwoznicki/temp-clipped-tiles-debugging-style

Let me know if you run into any issues getting this to run. I haven't tried running `tileserver-gl` on a different machine yet.

Also, do you know if there's a way to log messages within C++ and get them to show up on the console when running from NodeJS? As a sanity check, I'm trying to log the value of `mode` in https://github.com/acalcutt/maplibre-gl-native/blob/main/platform/node/src/node_map.cpp, but I haven't managed to get anything to log to the console when running the `tileserver-gl` command.

**Comment by dwoznicki** [comment]
It's probably worth noting that my setup is a bit unusual. I'm using Tegola as my vector tile server with TileServer GL as my rasterizer. So it's possible that if the vector tile needs to be prepared in a special way (e.g. provide extra details about nearby tiles?), my tile server is not doing so.

**Comment by acalcutt** [comment]
Did you install this as a node package in global mode? using 'npm install -g @acalcutt/tileserver-gl'. i was having issues getting that to work the other day so really just curious.

Did you make sure to clear your browser cache, possibly an old tile could be cached (I saw that when i first migrated)

I tried to see if I could use your style with my openmaptiles source but it seems to be a lot different of a format, and i wasn't able to use your source.

In raster mode all the rendering takes place in maplibre-gl-native, so It shouldn't matter if your vector source is different i wouldn't think.

**Comment by dwoznicki** [comment]
Also, not all tiles appear to be cut off. All the labels in the two tiles below are properly joined.

![image](https://user-images.githubusercontent.com/13933454/190040897-b7700dc2-ad32-4657-bf98-79eb9c0b3e4c.png)

![image](https://user-images.githubusercontent.com/13933454/190040990-bbcd74c3-0e91-408c-95f6-8f9178af740e.png)

**Comment by acalcutt** [comment]
If you look at massachusetts, do you see trimming in North Adams like https://github.com/maplibre/maplibre-gl-native/issues/284 , that was right on a tile line

I suppose maybe your vector tile source could be trimming before in gets to tileserver-gl. That tile vector tile source feed into Tileserver?

**Comment by acalcutt** [comment]
And I guess one more question for testing would be, does it work in https://github.com/maptiler/tileserver-gl using mapbox-native?

**Comment by dwoznicki** [comment]
> Did you install this as a node package in global mode? using 'npm install -g @acalcutt/tileserver-gl'. i was having issues getting that to work the other day so really just curious.

I just today changed `@acalcutt/tileserver-gl` to be project local, but I did have it installed globally for a couple months without any issue. That said, it was only *kinda* global, since I'm using `nvm` as my NodeJS version manager, and `nvm` maintains separate NodeJS binaries for each user.

> Did you make sure to clear your browser cache, possibly an old tile could be cached (I saw that when i first migrated)

I've tried hard refreshing (CTRL + SHIFT + r) and keeping the "Disable cache" option in Chrome checked while reloading. No luck with either.

> I tried to see if I could use your style with my openmaptiles source but it seems to be a lot different of a format, and i wasn't able to use your source.

Yeah, I ended up creating a custom data format for my vector tiles, so I don't expect it to work with other tile sources.

> If you look at massachusetts, do you see trimming in North Adams like https://github.com/maplibre/maplibre-gl-native/issues/284 , that was right on a tile line

It's a little tough to say because my styling is so different. I guess the answer is that I see some clipping, but not the same clipping.

![image](https://user-images.githubusercontent.com/13933454/190042705-8afdc34d-8f9b-463f-a975-6f33933d0c43.png)

> And I guess one more question for testing would be, does it work in https://github.com/maptiler/tileserver-gl using mapbox-native?

That's a really good idea. I'll check and get back to you (probably tomorrow).

**Comment by acalcutt** [comment]
I did some search on tegola label clipping and ran into this thread. somewhat similar

https://github.com/go-spatial/tegola/issues/562

**Comment by acalcutt** [comment]
Using some HAProxy magic I was able to get around the cross site blocking issue I was having testing your style.

I definitely confirm clipping all over the place when using that source
https://tiles.wifidb.net/styles/ntk/?raster#8/37.784/-121.124

**Comment by acalcutt** [comment]
Same thing in Maptiler TileServer-GL 3.1.1 

![image](https://user-images.githubusercontent.com/3792408/190053775-ed2bdfe1-f720-4b15-9865-317d91cc1ccd.png)

**Comment by dwoznicki** [comment]
> Same thing in Maptiler TileServer-GL 3.1.1

Mmm, yeah sure enough. I also tried adding the `dont_clip` attribute to my label layers from the Tegola issue you found, but that didn't do the trick, sadly. I suppose I'm not surprised though, since really what my tile server is sending is a single point with the label as an attribute, and I don't imagine the point is being clipped.

Actually, do you know how `mbgl::MapMode::Tile` works? It looks like the labels are (sometimes) not being rendered on tiles which don't contain the label point, which makes sense if each tile is rendered in isolation, but I imagine that can't be the case for tile mode because MapLibre is somehow figuring out that labels sometimes spill into adjacent tiles.

**Comment by dwoznicki** [comment]
Okay, found out something else interesting.

It looks like the places in the map with properly joined labels across multiple tiles are working because the PNG images are being rasterized from the same underlying PBF file. Using my example from above, tile `8/40/98.png`

![image](https://user-images.githubusercontent.com/13933454/190274070-b16b9c69-a328-43d4-822b-26a66cc699b2.png)

and `8/41/98.png`

![image](https://user-images.githubusercontent.com/13933454/190274195-ffc72a7d-9694-470f-b8ce-3f2177c3c9f5.png)


have properly joined labels for "San Francisco" and "Berkeley".

![image](https://user-images.githubusercontent.com/13933454/190274307-9cd34c7b-dba3-4845-b2f4-53c4280396d9.png)

When I modified my Tegola server to log which files were being requested, I noticed that the same PBF file was being requested for both.

```
2022-09-14 15:19:58 [DEBUG] middleware_tile_cache.go:81: cached tile /maps/osm/7/20/49.pbf
2022-09-14 15:20:02 [DEBUG] middleware_tile_cache.go:81: cached tile /maps/osm/7/20/49.pbf
```

However, when I check tiles where the label is cut off, such as `8/41/98.png`

![image](https://user-images.githubusercontent.com/13933454/190274627-464bd25f-0d72-4d52-bd27-a1fba216bfe3.png)


and `8/42/98.png`

![image](https://user-images.githubusercontent.com/13933454/190274773-6bc5a5fa-653e-4340-8766-9edfaf0eaea4.png)

(result on the map)

![image](https://user-images.githubusercontent.com/13933454/190274924-a664a1e2-900c-49c7-a254-ee18730c46c8.png)

I noticed that two different PBF files were being requested from my server.

```
2022-09-14 15:23:01 [DEBUG] middleware_tile_cache.go:81: cached tile /maps/osm/7/21/49.pbf
2022-09-14 15:23:41 [DEBUG] middleware_tile_cache.go:81: cached tile /maps/osm/7/20/49.pbf
```

I wonder if I need to somehow get TileServer GL/MapLibre GL Native to load adjacent PBF tiles.

**Comment by dwoznicki** [comment]
So I just found a much easier way to confirm my suspicion. In file `maplibre-gl-native/platform/node/src/node_map.cpp`, if I change line

```cpp
mbgl::MapDebugOptions debugOptions = mbgl::MapDebugOptions::NoDebug;
```

to

```cpp
mbgl::MapDebugOptions debugOptions = mbgl::MapDebugOptions::TileBorders;
```

and recompile + restart TileServer GL with the updated `mbgl.node` binary, I see that the labels are cut off exactly at the tile boundaries.

![image](https://user-images.githubusercontent.com/13933454/190281408-e39aeecc-b3d0-4798-b20b-c6492399c3a4.png)

I believe this is what you were checking with https://github.com/maplibre/maplibre-gl-native/issues/284#issuecomment-1146736226, but I just want to double check that if you turn on `mbgl::MapDebugOptions::TileBorders;` for your map style, the labels are rendered correctly across tile boundaries.

**Comment by dwoznicki** [comment]
@acalcutt I got it! I needed to add [`symbol-avoid-edges`](https://maplibre.org/maplibre-gl-js-docs/style-spec/layers/#layout-symbol-symbol-avoid-edges) to my `style.json` to void rendering labels that are too close to the edge of a tile.

Do you have something similar in your style by chance?

**Comment by acalcutt** [comment]
This is my style https://github.com/acalcutt/wifidb-tileserver-gl/blob/master/tileserver-gl/styles/WDB_OSM/style.json . doesn't looks like I have '[symbol-avoid-edges](https://maplibre.org/maplibre-gl-js-docs/style-spec/layers/#layout-symbol-symbol-avoid-edges)'

Also, i know this is closed, but just for informational purposes, My understanding of Tile Mode is the if you request something like a 512x512 image, it actually renders a little bit over that, adding a [padding of 1024 to each side](https://github.com/maplibre/maplibre-gl-native/blob/main/src/mbgl/text/collision_index.cpp#L26-L50). This bit of overdraw allows it to know labels that might have started in the next tile.

**Comment by dwoznicki** [comment]
> doesn't looks like I have '[symbol-avoid-edges](https://maplibre.org/maplibre-gl-js-docs/style-spec/layers/#layout-symbol-symbol-avoid-edges)'

Interesting. So if you turn on `mbgl::MapDebugOptions::TileBorders`, do your labels render properly between red lines?
