### ISSUE TITLE
Chinese/Japanese characters not being rendered on raster map

### ISSUE THREAD

**Issue by dwoznicki** [acalcutt/tileserver-gl#73]
I'm having trouble getting Chinese/Japanese names to show up on my raster map. Oddly enough, I do not have this problem with my vector tiles.

Here's a rendered vector tile from within Tokyo.

![image](https://user-images.githubusercontent.com/13933454/212444908-c258636f-5551-4807-b816-5fbe43d95edd.png)

Here's roughly the same raster tile.

![image](https://user-images.githubusercontent.com/13933454/212444948-9faf1019-7a8a-41fd-a9c4-c9dfabca8e13.png)

When I modify my style.json to render road label class instead of road name, we can see that there are a at least a few road labels within the tile.

![image](https://user-images.githubusercontent.com/13933454/212445108-b632092a-0b77-4e4a-b47f-e9faef88bae3.png)

I think this is probably an issue with my style.json, or maybe my fonts, because I see that other styles successfully render Chinese/Japanese labels. But I'm having trouble figuring out what could be going wrong, since my vector tiles seem fine.

Do you have any advice for debugging this issue?

tileserver-gl version

```
@acalcutt/tileserver-gl@5.2.0
```

OS

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

If it's of any use, you can find the frontend for my tileserver-gl here: http://flan.nettoolkit.com:8005/

**Comment by dwoznicki** [comment]
Oh, I think it's actually just an issue with Open Sans. Swapping to Noto Sans gives me a tile with proper road names. That's strange.. I wonder if my vector map is quietly fixing missing glyphs with fonts from my local computer.

**Comment by acalcutt** [comment]
I think thats truw btw. In the vector map using maplibre-gl-js it is able to download the missing fonts in the browser. When using maplibre-native in the raster maps, it needs them to be in the folder.

**Comment by acalcutt** [comment]
btw, I have moved most development to the official https://github.com/maptiler/tileserver-gl . I am and admin there now and most changes that were in my fork here are there now. I still use this fork for testing and development, but I would say the official branch should be a little more stable.
